template: |
  ## Changes

  $CHANGES
autolabeler:
  - label: bug
    branch:
      - "/^fix[/-].+/"
      - "/^bugfix[/-].+/"
  - label: documentation
    branch:
      - "/doc(umentation)[/-].+/"
    files:
      - "*.md"
  - label: enhancement
    branch:
      - "/(feature/enhancement|improve)[/-].+/"
  - label: refactor
    branch:
      - "/(refactor|refactoring)[/-].+/"
