name: Python CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main*
      - dev
      - release/*
env:
  UV_VERSION: 0.5.3
jobs:
  python-ci:
    strategy:
      matrix:
        command:
          - install_cmd: uv sync --frozen
            run_cmd: uv run ruff check
          - install_cmd: uv sync --frozen
            run_cmd: uv run pyright
          - install_cmd: uv sync --frozen --all-extras
            run_cmd: uv run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Instal uv
        run: |
          set -eux -o pipefail -o posix
          curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh
          echo "${HOME}/.local/bin" >> "$GITHUB_PATH"
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: ${{ matrix.command.install_cmd }}
      - name: Run ${{ matrix.command.run_cmd }}
        run: ${{ matrix.command.run_cmd }}
