name: Python CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main*
      - dev
      - release/*
jobs:
  python-ci:
    strategy:
      matrix:
        command:
          - install_cmd: uv sync --frozen
            run_cmd: uv run ruff check
          - install_cmd: uv sync --frozen
            run_cmd: uv run pyright
          - install_cmd: uv sync --frozen --all-extras
            run_cmd: uv run pytest
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/setup-uv@v4
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: ${{ matrix.command.install_cmd }}
      - name: Run ${{ matrix.command.run_cmd }}
        run: ${{ matrix.command.run_cmd }}
