---
#
# PRs for release/* branch
#
name: Release Drafter (autolabeler)
on:
  workflow_dispatch:
  pull_request:
    branches:
      - release/*
    types:
      - opened
      - reopened
      - synchronize
  workflow_call:
permissions:
  contents: read
jobs:
  autolabel:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Create a PRs message
        # https://github.com/release-drafter/release-drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-autolabel.yml
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
