name: Release & PyPI Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
env:
  UV_VERSION: 0.4.9
defaults:
  run:
    shell: bash -eux -o pipefail -o posix {0}
jobs:
  update_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract package version
        id: package_version
        # https://github.com/freshautomations/stoml/releases
        run: |
          package_version=$(
            PYTHONPATH='src/pydantic_config_parser' \
              python3 -c 'from __about__ import __version__; print(__version__)'
          )
          echo "package_version=${package_version}" >> $GITHUB_OUTPUT
      - name: Push tag
        run: |
          set -eux -o pipefail
          git tag v${{ steps.package_version.outputs.package_version }}
          git push origin refs/tags/v${{ steps.package_version.outputs.package_version }}
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          version: ${{ steps.package_version.outputs.package_version }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Instal uv
        run: |
          set -eux -o pipefail -o posix
          curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh
          echo PATH="${HOME}/.cargo/bin:${PATH}" >> "${GITHUB_ENV}"
      - uses: actions/checkout@v4
      - name: Build
        run: uvx --from build pyproject-build --installer uv
      - name: upload dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
  pypi-publish: # https://github.com/pypa/gh-action-pypi-publish
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs:
      - release-build
    environment:
      name: pypi
      url: https://pypi.org/p/pydantic-config-parser
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
